apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-process
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: video-process
  template:
    metadata:
      labels:
        app: video-process
    spec:
      containers:
      - name: video-process
        image: 192.168.56.10:5000/video-process
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "700Mi"
      schedulerName: rl-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: video-process
  namespace: openfaas-fn
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 1234
  selector:
    app: video-process

---
apiVersion: v1
kind: Service
metadata:
  name: video-process-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 1234
  selector:
    app: video-process
