apiVersion: apps/v1
kind: Deployment
metadata:
  name: dd
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dd
  template:
    metadata:
      labels:
        app: dd
    spec:
      containers:
      - name: dd
        image: 192.168.56.10:5000/dd
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "200Mi"
      schedulerName: rl-scheduler

---

apiVersion: v1
kind: Service
metadata:
  name: dd-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: dd
