apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-process
  namespace: openfaas-fn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-process
  template:
    metadata:
      labels:
        app: image-process
    spec:
      containers:
      - name: image-proces
        image: 192.168.56.10:5000/image-process
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "400m"
            memory: "500Mi"
      schedulerName: rl-scheduler

---
apiVersion: v1
kind: Service
metadata:
  name: image-process
  namespace: openfaas-fn
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: image-process

---
apiVersion: v1
kind: Service
metadata:
  name: image-process-external
  namespace: openfaas-fn
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: image-process
